############################################
######  Config YAML ########################
############################################

references:
  hg38_part:
    - normal_1
    - normal_2
    - normal_3
